### ISSUE TITLE
Edit option is overlapped

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#21]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url : https://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , PC
Step 5 : Open in browser,google chrome
Step 6 : In the above given link page it is observed that all edit options are overlapped as shown
![image](https://cloud.githubusercontent.com/assets/23308564/20090397/e6f5ccb6-a5b2-11e6-86ec-bd1dc0def1ce.png)

**Comment by debasis123nandi** [comment]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url : http://wipro48ocphrfau.devcloud.acquia-sites.com/responsibility
Step 4 : In device , PC
Step 5 : Open in browser,google chrome
Step 6 : In the above given link page it is observed that all edit options are overlapped as shown
![image](https://cloud.githubusercontent.com/assets/23308564/20127853/3c93aca4-a669-11e6-993d-43ebf94d216b.png)

**Comment by arpita123das** [comment]
Issue is resolved
URL:https://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
![solution](https://cloud.githubusercontent.com/assets/23329067/20137356/ed0f7758-a69f-11e6-9851-ed15bf5e820d.PNG)

**Comment by debasis123nandi** [comment]
Still the issue persist ::
url :: https://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
browser :: chrome
**shown highlighted**
![image](https://cloud.githubusercontent.com/assets/23308564/20164732/e0f04d8e-a72c-11e6-9880-649ec14335d8.png)

**Comment by debasis123nandi** [comment]
In addition ::
url :: https://wipro48ocphrfau.devcloud.acquia-sites.com/responsibility
browser :: chrome 

Highlighted edit is getting overlapped

![image](https://cloud.githubusercontent.com/assets/23308564/20170067/c67d1d64-a750-11e6-804e-5879493314b1.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
and http://wipro48ocphrfau.devcloud.acquia-sites.com/responsibility
![solutions](https://cloud.githubusercontent.com/assets/23329067/20591785/5653e396-b250-11e6-9526-fe6b65e0e448.PNG)

**Comment by debasis123nandi** [comment]
Its fine now
